CREATE TABLE EMPLOYEE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255),
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS;
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT;