CREATE TABLE OFFICE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE OFFICE ADD CONSTRAINT OFFICE_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS;